### PR TITLE
Add new `/v2/farcaster/feed/for_you` API to NodeJS SDK [NEYN-1882]

### PR DESCRIPTION
**Pull request by tybook**
https://github.com/neynarxyz/api/pull/517
https://github.com/neynarxyz/OAS/pull/145

### CODE REVIEW

**Comment by kale5195** [comment]
Hi @tybook , the for-you api is not able to call from neynar-api-client, is this a bug?

**Comment by tybook** [comment]
> Hi @tybook , the for-you api is not able to call from neynar-api-client, is this a bug?

Can you give more specifics on reproducing the problem?

**Comment by kale5195** [comment]
I usually call the api like this way: 
````
const neynarClient = new NeynarAPIClient(process.env.NEYNAR_API_KEY)

const res = await neynarClient.fetchFeed("following", {
          fid: fid,
          withRecasts: false,
          limit: PageSize,
          cursor: cursor,
        });
```

However, cannot find the feed-for-you api there.

**Comment by tybook** [comment]
> @tybook I usually call the api like this way:
> 
> ```
> const neynarClient = new NeynarAPIClient(process.env.NEYNAR_API_KEY)
> 
> const res = await neynarClient.fetchFeed("following", {
>           fid: fid,
>           withRecasts: false,
>           limit: PageSize,
>           cursor: cursor,
>         });
> ```
> 
> However, cannot find the feed-for-you api there.

This is fixed in v1.33.1 just released (see https://github.com/neynarxyz/nodejs-sdk/pull/126). So something like this should work now:
```
const res = await neynarClient.fetchFeedForYou(
    194, {
      limit: 5,
      cursor: undefined,
    });
```

**Pull request merged**
